# -*- coding: utf-8 -*-
#
# Copyright (C) 2021 Max-Planck-Gesellschaft zur Förderung der Wissenschaften e.V. (MPG),
# acting on behalf of its Max Planck Institute for Intelligent Systems and the
# Max Planck Institute for Biological Cybernetics. All rights reserved.
#
# Max-Planck-Gesellschaft zur Förderung der Wissenschaften e.V. (MPG) is holder of all proprietary rights
# on this computer program. You can only use this computer program if you have closed a license agreement
# with MPG or you get the right to use the computer program from someone who is authorized to grant you that right.
# Any use of the computer program without a valid license is prohibited and liable to prosecution.
# Contact: ps-license@tuebingen.mpg.de
#
# If you use this code in a research publication please cite the following:
#
# @conference{AMASS:ICCV:2019,
#   title = {{AMASS}: Archive of Motion Capture as Surface Shapes},
#   author = {Mahmood, Naureen and Ghorbani, Nima and Troje, Nikolaus F. and Pons-Moll, Gerard and Black, Michael J.},
#   booktitle = {International Conference on Computer Vision},
#   pages = {5442--5451},
#   month = oct,
#   year = {2019},
#   month_numeric = {10}
# }
#
# You can find complementary content at the project website: https://amass.is.tue.mpg.de/
#
# Code Developed by:
# Nima Ghorbani <https://nghorbani.github.io/>
# Naureen Mahmood <https://ps.is.tuebingen.mpg.de/person/nmahmood>
# Matthew Loper <https://ps.is.mpg.de/~mloper>
# While at Max-Planck Institute for Intelligent Systems, Tübingen, Germany
#
# 2021.06.18
general_labels_map = {'HEAD_TOP': 'ARIEL',
                      'TOPBACK': 'C7',
                      'NECK_BASE': 'C7',
                      'CHEST': 'CLAV',
                      'UPTHRX': 'CLAV',
                      'L_ANKLE': 'LANK',
                      'L_ANK': 'LANK',
                      'L_UPBACK': 'LBAK',
                      'LBAC': 'LBAK',
                      'LBAC-1': 'LBAK',
                      'L_BICEP': 'LBCEP',
                      'L_EAR': 'LBHD',
                      'NEWLSHO': 'LBCEP',
                      'NEWRSHO': 'RBCEP',
                      'NEWLBAC': 'LNWST',
                      'NEWRBAC': 'RNWST',
                      'LBSHO': 'LBSH',
                      'L_B_SHOULDER': 'LBSH',
                      'L_B_WAIST': 'LBWT',
                      'L_BWT': 'LBWT',
                      'LPSI': 'LBWT',
                      'L_CALF': 'LCLF',
                      'LIBH': 'LEBHI',
                      'LMBH': 'LEBHM',
                      'LPBH': 'LEBHP',
                      'LRBH': 'LEBHR',
                      'LIDIP': 'LEIDIP',
                      'L_ELBOW': 'LELB',
                      'L_INELBOW': 'LELBIN',
                      'LILB': 'LELBIN',
                      'LIEL': 'LELBIN',
                      'LMDIP': 'LEMDIP',
                      'LPDIP': 'LEPDIP',
                      'LPPIP': 'LEPPIP',
                      'LPTIP': 'LEPTIP',
                      'LRDIP': 'LERDIP',
                      'LRPIP': 'LERPIP',
                      'LRTIP': 'LERTIP',
                      'LTMP': 'LETMP',
                      'LTPIPI': 'LETPIPIN',
                      'LTPIPO': 'LTHM4',
                      'HEAD_OFFSET': 'LFHD',
                      'L_PINKY': 'LFIN',
                      'LOHAND': 'LFIN',
                      'L_FIN': 'LFIN',
                      'LPHLX5': 'LFIN',
                      'L_FOREARM': 'LFRM',
                      'LARM': 'LFRM',
                      'LFRA': 'LFRM',
                      'LWRE': 'LFRM',
                      'LWRI': 'LFRMIN',
                      'L_F_SHOULDER': 'LFSH',
                      'LASI': 'LFWT',
                      'L_F_WAIST': 'LFWT',
                      'L_FWT': 'LFWT',
                      'L_HEEL': 'LHEE',
                      'LHEL': 'LHEE',
                      'LANKIN': 'LHEEI',
                      'LANKI': 'LHEEI',
                      'LIPIP': 'LIDX1',
                      'LEIPIP': 'LIDX1',
                      'LITIP': 'LIDX3',
                      'LEITIP': 'LIDX3',
                      'L_INWRIST': 'LIWR',
                      'LWRA': 'LIWR',
                      'LWRST': 'LIWR',
                      'L_OUTKNEE': 'LKNE',
                      'L_KNEE': 'LKNE',
                      'L_INKNEE': 'LKNI',
                      'LKNEIN': 'LKNI',
                      'LMPIP': 'LMID1',
                      'LEMPIP': 'LMID1',
                      'LMTIP': 'LMID3',
                      'LEMTIP': 'LMID3',
                      'L_BIGTOE': 'LMT1',
                      'L_PINKYTOE': 'LMT5',
                      'L_OUTWRIST': 'LOWR',
                      'LWRB': 'LOWR',
                      'L_WRIST': 'LOWR',
                      # 'LEPTIP': 'LPNK3',
                      'LMWT': 'LPRFWT',
                      'LTOE5': 'LRSTBEEF',
                      'L_MIDBACK': 'LSCAP',
                      'L_SHIN': 'LSHN',
                      'LSHIN': 'LSHN',
                      'L_SHOULDER': 'LSHOUP',
                      'LHIP': 'LTHI',
                      'L_HIP': 'LTHI',
                      'L_HAM': 'LTHI',
                      'L_THIGH': 'LTHILO',
                      'LTHIGH': 'LTHILO',
                      'LTTIP': 'LTHM3',
                      # 'LETTIP': 'LTHM3',
                      'L_THUMB': 'LTHMB',
                      'LIHAND': 'LTHMB',
                      'LPHLX1': 'LTHMB',
                      'LLEG': 'LTIB',
                      'L_TOETIP': 'LTOE',
                      'LTOE1': 'LTOE',
                      'L_TRICEP': 'LUPA',
                      'R_ANKLE': 'RANK',
                      'R_ANK': 'RANK',
                      'R_UPBACK': 'RBAK',
                      'RBAC': 'RBAK',
                      'RBAC-1': 'RBAK',
                      'R10': 'RBAK',
                      'OFFSET': 'RBAK',
                      'R_BICEP': 'RBCEP',
                      'R_EAR': 'RBHD',
                      'RBSHO': 'RBSH',
                      'R_B_SHOULDER': 'RBSH',
                      'RPSI': 'RBWT',
                      'R_B_WAIST': 'RBWT',
                      'R_BWT': 'RBWT',
                      'R_CALF': 'RCLF',
                      'R_ELBOW': 'RELB',
                      'R_INELBOW': 'RELBIN',
                      'RILB': 'RELBIN',
                      'RIEL': 'RELBIN',
                      'R_PINKY': 'RFIN',
                      'ROHAND': 'RFIN',
                      'R_FIN': 'RFIN',
                      'RPHLX5': 'RFIN',
                      'R_FOREARM': 'RFRM',
                      'RARM': 'RFRM',
                      'RFRA': 'RFRM',
                      'RWRE': 'RFRM',
                      'RWRI': 'RFRMIN',
                      'R_F_SHOULDER': 'RFSH',
                      'RASI': 'RFWT',
                      'R_F_WAIST': 'RFWT',
                      'R_FWT': 'RFWT',
                      'R_HEEL': 'RHEE',
                      'RHEL': 'RHEE',
                      'RANKIN': 'RHEEI',
                      'RANKI': 'RHEEI',
                      'RIBH': 'RIBHI',
                      'RMBH': 'RIBHM',
                      'RPBH': 'RIBHP',
                      'RRBH': 'RIBHR',
                      'RITIP': 'RIDX3',
                      'RIITIP': 'RIDX3',
                      'RIDIP': 'RIIDIP',
                      'RIPIP': 'RIIPIP',
                      'RMDIP': 'RIMDIP',
                      'RMPIP': 'RIMPIP',
                      'RPDIP': 'RIPDIP',
                      'RPPIP': 'RIPPIP',
                      'RRDIP': 'RIRDIP',
                      'RRPIP': 'RIRPIP',
                      'RTMP': 'RITMP',
                      'RTPIPI': 'RITPIPIN',
                      'RTPIPO': 'RITPIPOUT',
                      'RTTIP': 'RITTIP',
                      'R_INWRIST': 'RIWR',
                      'RWRA': 'RIWR',
                      'R_OUTKNEE': 'RKNE',
                      'R_KNEE': 'RKNE',
                      'R_INKNEE': 'RKNI',
                      'RKNEIN': 'RKNI',
                      'RMTIP': 'RMID3',
                      'RIMTIP': 'RMID3',
                      'R_BIGTOE': 'RMT1',
                      'R_PINKYTOE': 'RMT5',
                      'R_OUTWRIST': 'ROWR',
                      'RWRB': 'ROWR',
                      'R_WRIST': 'ROWR',
                      'RPTIP': 'RPNK3',
                      'RIPTIP': 'RPNK3',
                      'RMWT': 'RPRFWT',
                      'RRTIP': 'RRNG3',
                      'RIRTIP': 'RRNG3',
                      'RTOE5': 'RRSTBEEF',
                      'R_MIDBACK': 'RSCAP',
                      'R_SHIN': 'RSHN',
                      'RSHIN': 'RSHN',
                      'R_SHOULDER': 'RSHOUP',
                      'RHIP': 'RTHI',
                      'R_HIP': 'RTHI',
                      'R_HAM': 'RTHI',
                      'R_THIGH': 'RTHILO',
                      'RTHIGH': 'RTHILO',
                      'R_THUMB': 'RTHMB',
                      'RIHAND': 'RTHMB',
                      'RPHLX1': 'RTHMB',
                      'RLEG': 'RTIB',
                      'R_TOETIP': 'RTOE',
                      'RTOE1': 'RTOE',
                      'R_TRICEP': 'RUPA',
                      'STERNUM': 'STRN',
                      'SETRNUM': 'STRN',
                      'LOTHRX': 'STRN',
                      'LOBACK': 'T10',
                      'MIDBACK': 'T8',
                      'MID_BACK': 'T8',
                      'ghost': 'nan',
                      'NaN': 'nan',
                      "Skeleton5ChestHFront": "CLAV",
                        "Skeleton5ChestLFront": "STRN",
                        "Skeleton5ChestHBack": "C7",
                        "Skeleton5ChestLBack": "T10",

                        "Skeleton5HeadRFront": "RFHD",
                        "Skeleton5HeadRBack": "RBHD",
                        "Skeleton5HeadTop": "ARIEL",
                        "Skeleton5HeadLFront": "LFHD",
                        "Skeleton5HeadLBack": "LBHD",

                        "Skeleton5WaistRFront": "RFWT",
                        "Skeleton5WaistLFront": "LFWT",
                        "Skeleton5WaistMFront": "MFWT",
                        "Skeleton5WaistRBack": "RBWT",
                        "Skeleton5WaistLBack": "LBWT",
                        "Skeleton5WaistMBack": "MBWT",
                        
                        "Skeleton5RShoulderFront": "RFSH",
                        "Skeleton5RShoulderBack": "RBSH",
                        "Skeleton5LShoulderFront": "LFSH",
                        "Skeleton5LShoulderBack": "LBSH",
                        "Skeleton5RArm": "RUPA",
                        "Skeleton5LArm": "LUPA",
                        "Skeleton5RForeArm": "RFRM",
                        "Skeleton5LForeArm": "LFRM",
                        "Skeleton5RElbowHigh": "RELB",
                        "Skeleton5RElbowLow": "RELBIN",
                        "Skeleton5LElbowHigh": "LELB",
                        "Skeleton5LElbowLow": "LELBIN",
                        "Skeleton5RWristIn": "RIWR",
                        "Skeleton5RWristOut": "ROWR",
                        "Skeleton5LWristIn": "LIWR",
                        "Skeleton5LWristOut": "LOWR",

                        "Skeleton5RHandIn": "RTHMB",
                        "Skeleton5RHandOut": "RFIN",
                        "Skeleton5LHandIn": "LTHMB",
                        "Skeleton5LHandOut": "LFIN",
                        "Skeleton5LThigh": "LTHI",
                        "Skeleton5RThigh": "RTHI",
                        "Skeleton5LShin": "LSHN",
                        "Skeleton5RShin": "RSHN",
                        "Skeleton5LKneeOut": "LKNE",
                        "Skeleton5LKneeIn": "LKNI",
                        "Skeleton5RKneeOut": "RKNE",
                        "Skeleton5RKneeIn": "RKNI",
                        "Skeleton5LAnkleOut": "LANK",
                        "Skeleton5RAnkleOut": "RANK",
                        "Skeleton5RHeel": "RHEE",
                        "Skeleton5LHeel": "LHEE",
                        "Skeleton5LToeTip": "LTOE",
                        "Skeleton5LToeIn": "LMT1",
                        "Skeleton5LToeOut": "LMT5",
                        "Skeleton5RToeTip": "RTOE",
                        "Skeleton5RToeIn": "RMT1",
                        "Skeleton5RToeOut": "RMT5",

                        "Skeleton3ChestHFront": "CLAV",
                        "Skeleton3ChestLFront": "STRN",
                        "Skeleton3ChestHBack": "C7",
                        "Skeleton3ChestLBack": "T10",

                        "Skeleton3HeadRFront": "RFHD",
                        "Skeleton3HeadRBack": "RBHD",
                        "Skeleton3HeadTop": "ARIEL",
                        "Skeleton3HeadLFront": "LFHD",
                        "Skeleton3HeadLBack": "LBHD",

                        "Skeleton3WaistRFront": "RFWT",
                        "Skeleton3WaistLFront": "LFWT",
                        "Skeleton3WaistMFront": "MFWT",
                        "Skeleton3WaistRBack": "RBWT",
                        "Skeleton3WaistLBack": "LBWT",
                        "Skeleton3WaistMBack": "MBWT",
                        
                        "Skeleton3RShoulderFront": "RFSH",
                        "Skeleton3RShoulderBack": "RBSH",
                        "Skeleton3LShoulderFront": "LFSH",
                        "Skeleton3LShoulderBack": "LBSH",
                        "Skeleton3RArm": "RUPA",
                        "Skeleton3LArm": "LUPA",
                        "Skeleton3RForeArm": "RFRM",
                        "Skeleton3LForeArm": "LFRM",
                        "Skeleton3RElbowHigh": "RELB",
                        "Skeleton3RElbowLow": "RELBIN",
                        "Skeleton3LElbowHigh": "LELB",
                        "Skeleton3LElbowLow": "LELBIN",
                        "Skeleton3RWristIn": "RIWR",
                        "Skeleton3RWristOut": "ROWR",
                        "Skeleton3LWristIn": "LIWR",
                        "Skeleton3LWristOut": "LOWR",

                        "Skeleton3RHandIn": "RTHMB",
                        "Skeleton3RHandOut": "RFIN",
                        "Skeleton3LHandIn": "LTHMB",
                        "Skeleton3LHandOut": "LFIN",
                        "Skeleton3LThigh": "LTHI",
                        "Skeleton3RThigh": "RTHI",
                        "Skeleton3LShin": "LSHN",
                        "Skeleton3RShin": "RSHN",
                        "Skeleton3LKneeOut": "LKNE",
                        "Skeleton3LKneeIn": "LKNI",
                        "Skeleton3RKneeOut": "RKNE",
                        "Skeleton3RKneeIn": "RKNI",
                        "Skeleton3LAnkleOut": "LANK",
                        "Skeleton3RAnkleOut": "RANK",
                        "Skeleton3RHeel": "RHEE",
                        "Skeleton3LHeel": "LHEE",
                        "Skeleton3LToeTip": "LTOE",
                        "Skeleton3LToeIn": "LMT1",
                        "Skeleton3LToeOut": "LMT5",
                        "Skeleton3RToeTip": "RTOE",
                        "Skeleton3RToeIn": "RMT1",
                        "Skeleton3RToeOut": "RMT5",

                        "Skeleton1ChestHFront": "CLAV",
                        "Skeleton1ChestLFront": "STRN",
                        "Skeleton1ChestHBack": "C7",
                        "Skeleton1ChestLBack": "T10",

                        "Skeleton1HeadRFront": "RFHD",
                        "Skeleton1HeadRBack": "RBHD",
                        "Skeleton1HeadTop": "ARIEL",
                        "Skeleton1HeadLFront": "LFHD",
                        "Skeleton1HeadLBack": "LBHD",

                        "Skeleton1WaistRFront": "RFWT",
                        "Skeleton1WaistLFront": "LFWT",
                        "Skeleton1WaistMFront": "MFWT",
                        "Skeleton1WaistRBack": "RBWT",
                        "Skeleton1WaistLBack": "LBWT",
                        "Skeleton1WaistMBack": "MBWT",
                        
                        "Skeleton1RShoulderFront": "RFSH",
                        "Skeleton1RShoulderBack": "RBSH",
                        "Skeleton1LShoulderFront": "LFSH",
                        "Skeleton1LShoulderBack": "LBSH",
                        "Skeleton1RArm": "RUPA",
                        "Skeleton1LArm": "LUPA",
                        "Skeleton1RForeArm": "RFRM",
                        "Skeleton1LForeArm": "LFRM",
                        "Skeleton1RElbowHigh": "RELB",
                        "Skeleton1RElbowLow": "RELBIN",
                        "Skeleton1LElbowHigh": "LELB",
                        "Skeleton1LElbowLow": "LELBIN",
                        "Skeleton1RWristIn": "RIWR",
                        "Skeleton1RWristOut": "ROWR",
                        "Skeleton1LWristIn": "LIWR",
                        "Skeleton1LWristOut": "LOWR",

                        "Skeleton1RHandIn": "RTHMB",
                        "Skeleton1RHandOut": "RFIN",
                        "Skeleton1LHandIn": "LTHMB",
                        "Skeleton1LHandOut": "LFIN",
                        "Skeleton1LThigh": "LTHI",
                        "Skeleton1RThigh": "RTHI",
                        "Skeleton1LShin": "LSHN",
                        "Skeleton1RShin": "RSHN",
                        "Skeleton1LKneeOut": "LKNE",
                        "Skeleton1LKneeIn": "LKNI",
                        "Skeleton1RKneeOut": "RKNE",
                        "Skeleton1RKneeIn": "RKNI",
                        "Skeleton1LAnkleOut": "LANK",
                        "Skeleton1RAnkleOut": "RANK",
                        "Skeleton1RHeel": "RHEE",
                        "Skeleton1LHeel": "LHEE",
                        "Skeleton1LToeTip": "LTOE",
                        "Skeleton1LToeIn": "LMT1",
                        "Skeleton1LToeOut": "LMT5",
                        "Skeleton1RToeTip": "RTOE",
                        "Skeleton1RToeIn": "RMT1",
                        "Skeleton1RToeOut": "RMT5",

                        "Skeleton2ChestHFront": "CLAV",
                        "Skeleton2ChestLFront": "STRN",
                        "Skeleton2ChestHBack": "C7",
                        "Skeleton2ChestLBack": "T10",

                        "Skeleton2HeadRFront": "RFHD",
                        "Skeleton2HeadRBack": "RBHD",
                        "Skeleton2HeadTop": "ARIEL",
                        "Skeleton2HeadLFront": "LFHD",
                        "Skeleton2HeadLBack": "LBHD",

                        "Skeleton2WaistRFront": "RFWT",
                        "Skeleton2WaistLFront": "LFWT",
                        "Skeleton2WaistMFront": "MFWT",
                        "Skeleton2WaistRBack": "RBWT",
                        "Skeleton2WaistLBack": "LBWT",
                        "Skeleton2WaistMBack": "MBWT",
                        
                        "Skeleton2RShoulderFront": "RFSH",
                        "Skeleton2RShoulderBack": "RBSH",
                        "Skeleton2LShoulderFront": "LFSH",
                        "Skeleton2LShoulderBack": "LBSH",
                        "Skeleton2RArm": "RUPA",
                        "Skeleton2LArm": "LUPA",
                        "Skeleton2RForeArm": "RFRM",
                        "Skeleton2LForeArm": "LFRM",
                        "Skeleton2RElbowHigh": "RELB",
                        "Skeleton2RElbowLow": "RELBIN",
                        "Skeleton2LElbowHigh": "LELB",
                        "Skeleton2LElbowLow": "LELBIN",
                        "Skeleton2RWristIn": "RIWR",
                        "Skeleton2RWristOut": "ROWR",
                        "Skeleton2LWristIn": "LIWR",
                        "Skeleton2LWristOut": "LOWR",

                        "Skeleton2RHandIn": "RTHMB",
                        "Skeleton2RHandOut": "RFIN",
                        "Skeleton2LHandIn": "LTHMB",
                        "Skeleton2LHandOut": "LFIN",
                        "Skeleton2LThigh": "LTHI",
                        "Skeleton2RThigh": "RTHI",
                        "Skeleton2LShin": "LSHN",
                        "Skeleton2RShin": "RSHN",
                        "Skeleton2LKneeOut": "LKNE",
                        "Skeleton2LKneeIn": "LKNI",
                        "Skeleton2RKneeOut": "RKNE",
                        "Skeleton2RKneeIn": "RKNI",
                        "Skeleton2LAnkleOut": "LANK",
                        "Skeleton2RAnkleOut": "RANK",
                        "Skeleton2RHeel": "RHEE",
                        "Skeleton2LHeel": "LHEE",
                        "Skeleton2LToeTip": "LTOE",
                        "Skeleton2LToeIn": "LMT1",
                        "Skeleton2LToeOut": "LMT5",
                        "Skeleton2RToeTip": "RTOE",
                        "Skeleton2RToeIn": "RMT1",
                        "Skeleton2RToeOut": "RMT5",

                        "Skeleton4ChestHFront": "CLAV",
                        "Skeleton4ChestLFront": "STRN",
                        "Skeleton4ChestHBack": "C7",
                        "Skeleton4ChestLBack": "T10",

                        "Skeleton4HeadRFront": "RFHD",
                        "Skeleton4HeadRBack": "RBHD",
                        "Skeleton4HeadTop": "ARIEL",
                        "Skeleton4HeadLFront": "LFHD",
                        "Skeleton4HeadLBack": "LBHD",

                        "Skeleton4WaistRFront": "RFWT",
                        "Skeleton4WaistLFront": "LFWT",
                        "Skeleton4WaistMFront": "MFWT",
                        "Skeleton4WaistRBack": "RBWT",
                        "Skeleton4WaistLBack": "LBWT",
                        "Skeleton4WaistMBack": "MBWT",
                        
                        "Skeleton4RShoulderFront": "RFSH",
                        "Skeleton4RShoulderBack": "RBSH",
                        "Skeleton4LShoulderFront": "LFSH",
                        "Skeleton4LShoulderBack": "LBSH",
                        "Skeleton4RArm": "RUPA",
                        "Skeleton4LArm": "LUPA",
                        "Skeleton4RForeArm": "RFRM",
                        "Skeleton4LForeArm": "LFRM",
                        "Skeleton4RElbowHigh": "RELB",
                        "Skeleton4RElbowLow": "RELBIN",
                        "Skeleton4LElbowHigh": "LELB",
                        "Skeleton4LElbowLow": "LELBIN",
                        "Skeleton4RWristIn": "RIWR",
                        "Skeleton4RWristOut": "ROWR",
                        "Skeleton4LWristIn": "LIWR",
                        "Skeleton4LWristOut": "LOWR",

                        "Skeleton4RHandIn": "RTHMB",
                        "Skeleton4RHandOut": "RFIN",
                        "Skeleton4LHandIn": "LTHMB",
                        "Skeleton4LHandOut": "LFIN",
                        "Skeleton4LThigh": "LTHI",
                        "Skeleton4RThigh": "RTHI",
                        "Skeleton4LShin": "LSHN",
                        "Skeleton4RShin": "RSHN",
                        "Skeleton4LKneeOut": "LKNE",
                        "Skeleton4LKneeIn": "LKNI",
                        "Skeleton4RKneeOut": "RKNE",
                        "Skeleton4RKneeIn": "RKNI",
                        "Skeleton4LAnkleOut": "LANK",
                        "Skeleton4RAnkleOut": "RANK",
                        "Skeleton4RHeel": "RHEE",
                        "Skeleton4LHeel": "LHEE",
                        "Skeleton4LToeTip": "LTOE",
                        "Skeleton4LToeIn": "LMT1",
                        "Skeleton4LToeOut": "LMT5",
                        "Skeleton4RToeTip": "RTOE",
                        "Skeleton4RToeIn": "RMT1",
                        "Skeleton4RToeOut": "RMT5",

                        "Skeleton6ChestHFront": "CLAV",
                        "Skeleton6ChestLFront": "STRN",
                        "Skeleton6ChestHBack": "C7",
                        "Skeleton6ChestLBack": "T10",

                        "Skeleton6HeadRFront": "RFHD",
                        "Skeleton6HeadRBack": "RBHD",
                        "Skeleton6HeadTop": "ARIEL",
                        "Skeleton6HeadLFront": "LFHD",
                        "Skeleton6HeadLBack": "LBHD",

                        "Skeleton6WaistRFront": "RFWT",
                        "Skeleton6WaistLFront": "LFWT",
                        "Skeleton6WaistMFront": "MFWT",
                        "Skeleton6WaistRBack": "RBWT",
                        "Skeleton6WaistLBack": "LBWT",
                        "Skeleton6WaistMBack": "MBWT",
                        
                        "Skeleton6RShoulderFront": "RFSH",
                        "Skeleton6RShoulderBack": "RBSH",
                        "Skeleton6LShoulderFront": "LFSH",
                        "Skeleton6LShoulderBack": "LBSH",
                        "Skeleton6RArm": "RUPA",
                        "Skeleton6LArm": "LUPA",
                        "Skeleton6RForeArm": "RFRM",
                        "Skeleton6LForeArm": "LFRM",
                        "Skeleton6RElbowHigh": "RELB",
                        "Skeleton6RElbowLow": "RELBIN",
                        "Skeleton6LElbowHigh": "LELB",
                        "Skeleton6LElbowLow": "LELBIN",
                        "Skeleton6RWristIn": "RIWR",
                        "Skeleton6RWristOut": "ROWR",
                        "Skeleton6LWristIn": "LIWR",
                        "Skeleton6LWristOut": "LOWR",

                        "Skeleton6RHandIn": "RTHMB",
                        "Skeleton6RHandOut": "RFIN",
                        "Skeleton6LHandIn": "LTHMB",
                        "Skeleton6LHandOut": "LFIN",
                        "Skeleton6LThigh": "LTHI",
                        "Skeleton6RThigh": "RTHI",
                        "Skeleton6LShin": "LSHN",
                        "Skeleton6RShin": "RSHN",
                        "Skeleton6LKneeOut": "LKNE",
                        "Skeleton6LKneeIn": "LKNI",
                        "Skeleton6RKneeOut": "RKNE",
                        "Skeleton6RKneeIn": "RKNI",
                        "Skeleton6LAnkleOut": "LANK",
                        "Skeleton6RAnkleOut": "RANK",
                        "Skeleton6RHeel": "RHEE",
                        "Skeleton6LHeel": "LHEE",
                        "Skeleton6LToeTip": "LTOE",
                        "Skeleton6LToeIn": "LMT1",
                        "Skeleton6LToeOut": "LMT5",
                        "Skeleton6RToeTip": "RTOE",
                        "Skeleton6RToeIn": "RMT1",
                        "Skeleton6RToeOut": "RMT5",

                        "Skeleton7ChestHFront": "CLAV",
                        "Skeleton7ChestLFront": "STRN",
                        "Skeleton7ChestHBack": "C7",
                        "Skeleton7ChestLBack": "T10",

                        "Skeleton7HeadRFront": "RFHD",
                        "Skeleton7HeadRBack": "RBHD",
                        "Skeleton7HeadTop": "ARIEL",
                        "Skeleton7HeadLFront": "LFHD",
                        "Skeleton7HeadLBack": "LBHD",

                        "Skeleton7WaistRFront": "RFWT",
                        "Skeleton7WaistLFront": "LFWT",
                        "Skeleton7WaistMFront": "MFWT",
                        "Skeleton7WaistRBack": "RBWT",
                        "Skeleton7WaistLBack": "LBWT",
                        "Skeleton7WaistMBack": "MBWT",
                        
                        "Skeleton7RShoulderFront": "RFSH",
                        "Skeleton7RShoulderBack": "RBSH",
                        "Skeleton7LShoulderFront": "LFSH",
                        "Skeleton7LShoulderBack": "LBSH",
                        "Skeleton7RArm": "RUPA",
                        "Skeleton7LArm": "LUPA",
                        "Skeleton7RForeArm": "RFRM",
                        "Skeleton7LForeArm": "LFRM",
                        "Skeleton7RElbowHigh": "RELB",
                        "Skeleton7RElbowLow": "RELBIN",
                        "Skeleton7LElbowHigh": "LELB",
                        "Skeleton7LElbowLow": "LELBIN",
                        "Skeleton7RWristIn": "RIWR",
                        "Skeleton7RWristOut": "ROWR",
                        "Skeleton7LWristIn": "LIWR",
                        "Skeleton7LWristOut": "LOWR",

                        "Skeleton7RHandIn": "RTHMB",
                        "Skeleton7RHandOut": "RFIN",
                        "Skeleton7LHandIn": "LTHMB",
                        "Skeleton7LHandOut": "LFIN",
                        "Skeleton7LThigh": "LTHI",
                        "Skeleton7RThigh": "RTHI",
                        "Skeleton7LShin": "LSHN",
                        "Skeleton7RShin": "RSHN",
                        "Skeleton7LKneeOut": "LKNE",
                        "Skeleton7LKneeIn": "LKNI",
                        "Skeleton7RKneeOut": "RKNE",
                        "Skeleton7RKneeIn": "RKNI",
                        "Skeleton7LAnkleOut": "LANK",
                        "Skeleton7RAnkleOut": "RANK",
                        "Skeleton7RHeel": "RHEE",
                        "Skeleton7LHeel": "LHEE",
                        "Skeleton7LToeTip": "LTOE",
                        "Skeleton7LToeIn": "LMT1",
                        "Skeleton7LToeOut": "LMT5",
                        "Skeleton7RToeTip": "RTOE",
                        "Skeleton7RToeIn": "RMT1",
                        "Skeleton7RToeOut": "RMT5",
                      }
